name: ci/smoke-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke-test:
    name: ci/smoke-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (optional)
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "no package.json — skipping npm install"
          fi

      - name: Run unit tests (optional)
        run: |
          if [ -f package.json ] && npm test --version >/dev/null 2>&1; then
            npm test
          else
            echo "no tests defined — skipping"
          fi

      - name: Smoke test (optional curl against PREVIEW_URL)
        env:
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }} # optional: set this if you want to curl preview
        run: |
          if [ -n "$PREVIEW_URL" ]; then
            http_status=$(curl -s -o /dev/null -w "%{http_code}" -X OPTIONS "$PREVIEW_URL/api/generate")
            echo "OPTIONS status: $http_status"
            if [ "$http_status" != "204" ] && [ "$http_status" != "200" ]; then
              echo "Preview health check failed: $http_status"
              exit 1
            fi
          else
            echo "PREVIEW_URL not set; skipping remote smoke test"
          fi
